### ISSUE TITLE
cannot join teams

### ISSUE THREAD

**Issue by concernedamongus** [cazzwastaken/based#5]
cannot join teams, and can't get into casual. it just gets you to spectator.

**Comment by WolfyCSGO** [comment]
cheap fix:

type joingame in the console

**Comment by KoC0de** [comment]
Hi!

Add this to the **START** of your CreateMove Hook:

```
if(cmd->commandNumber == 0)
	return false;
```

(it is very important that this is the first thing, that you do in your CreateMove Hook.)

**Comment by xiv1337** [comment]
> Hi!
> 
> Add this to the **START** of your CreateMove Hook:
> 
> ```
> if(cmd->commandNumber == 0)
> 	return false;
> ```
> 
> (it is very important that this is the first thing, that you do in your CreateMove Hook.)

wrong- you need to spoof the return address checks

**Comment by KoC0de** [comment]
> > Hi!
> > Add this to the **START** of your CreateMove Hook:
> > ```
> > if(cmd->commandNumber == 0)
> > 	return false;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (it is very important that this is the first thing, that you do in your CreateMove Hook.)
> 
> wrong- you need to spoof the return address checks

i think the return adress is already spoofed [here](https://github.com/cazzwastaken/based/blob/master/src/core/hooks.cpp#L39=)

**Comment by AdisonCavani** [comment]
> > > Hi!
> > > Add this to the **START** of your CreateMove Hook:
> > > ```
> > > if(cmd->commandNumber == 0)
> > > 	return false;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > (it is very important that this is the first thing, that you do in your CreateMove Hook.)
> > 
> > 
> > wrong- you need to spoof the return address checks
> 
> i think the return adress is already spoofed [here](https://github.com/cazzwastaken/based/blob/master/src/core/hooks.cpp#L39=)

Right now, it doesn't work.

You need to spoof the return adress, not just "bypass" it.
This library is helpful - [`danielkrupinski/x86RetSpoof`](https://github.com/danielkrupinski/x86RetSpoof).  

This is how I made it:
```cpp
bool __stdcall hooks::CreateMove(float frameTime, CUserCmd* cmd) noexcept
{
	static uintptr_t sequence = (uintptr_t)memory::PatternScan("client.dll", "FF 23");
	x86retspoof::invokeStdcall<bool>((uintptr_t)hooks::CreateMoveOriginal, sequence, frameTime, cmd);

	// Make sure this function is being called from CInput::CreateMove
	if (!cmd || !cmd->commandNumber)
		return false;

	// DO SOME STUFF HERE...

	return false;
}
```

**Comment by KoC0de** [comment]
> > > > Hi!
> > > > Add this to the **START** of your CreateMove Hook:
> > > > ```
> > > > if(cmd->commandNumber == 0)
> > > > 	return false;
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > (it is very important that this is the first thing, that you do in your CreateMove Hook.)
> > > 
> > > 
> > > wrong- you need to spoof the return address checks
> > 
> > 
> > i think the return adress is already spoofed [here](https://github.com/cazzwastaken/based/blob/master/src/core/hooks.cpp#L39=)
> 
> Right now, it doesn't work.
> 
> You need to spoof the return adress, not just "bypass" it. This library is helpful - [`danielkrupinski/x86RetSpoof`](https://github.com/danielkrupinski/x86RetSpoof).
> 
> This is how I made it:
> 
> ```c++
> bool __stdcall hooks::CreateMove(float frameTime, CUserCmd* cmd) noexcept
> {
> 	static uintptr_t sequence = (uintptr_t)memory::PatternScan("client.dll", "FF 23");
> 	x86retspoof::invokeStdcall<bool>((uintptr_t)hooks::CreateMoveOriginal, sequence, frameTime, cmd);
> 
> 	// Make sure this function is being called from CInput::CreateMove
> 	if (!cmd || !cmd->commandNumber)
> 		return false;
> 
> 	// DO SOME STUFF HERE...
> 
> 	return false;
> }
> ```

Thanks! <3
