### ISSUE TITLE
Click true menu

### ISSUE THREAD

**Issue by N3OA** [cazzwastaken/based#6]
When i press button in menu it also clicks into the game.
Tried to fix it but cant find a solution.

**Comment by astrouxer** [comment]
use the input interface

**Comment by N3OA** [comment]
I did but then i cant click anything when pressing insert

**Comment by maecry** [comment]
uhm input->enable_mouse(is_menu_open()) ???? 
psuedo code btw bet you gonna copy paste that and said code no w0rk
